version: "2.4"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    expose:
      - 9090
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./grafana/default.yml:/etc/grafana/provisioning/dashboards/default.yaml:ro
      # - ./grafana/proc-exporter-dashboard.json:/etc/grafana/provisioning/dashboards/proc-exporter-dashboard.json:ro
      - ./grafana/proc-exporter-dashboard.json:/var/lib/grafana/dashboards/proc-exporter-dashboard.json:ro
    ports:
      - 3000:3000
    # links:
    #   - prometheus
  proc-exporter:
    image: ncabatoff/process-exporter:latest
    command: --procfs /host/proc -procnames python,api -children
    restart: unless-stopped
    expose:
      - 9256
    ports:
      - 9256:9256
    volumes:
      - /proc:/host/proc:ro
    cap_add:
      - ALL
